# Colorscheme
include ./theme.conf

# Fonts
# BEGIN_KITTY_FONTS
font_family      family="MesloLGSDZ Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Font size
font_size 12

# Window appearance
hide_window_decorations titlebar-only
window_padding_width 5
